### ISSUE TITLE
Type isn't correct when using arithmetic metamethod

### ISSUE THREAD

**Issue by zxsleebu** [sumneko/vscode-lua#62] opened 2022-07-15 22:03 UTC
vec2_t.__div:
![Code_-_Insiders_nVr5CSjCmZ](https://user-images.githubusercontent.com/46263989/179317162-54673793-2552-426d-963d-0f3c06ae0346.png)
vec2_t:
![Code_-_Insiders_GVayEh6PEB](https://user-images.githubusercontent.com/46263989/179317443-3f7282de-bbb0-4b4a-a91f-566d42a50cc3.png)

Current behavior:
![Code_-_Insiders_m5W6tjXUzR](https://user-images.githubusercontent.com/46263989/179316727-edf0b3d8-52e6-40e6-b31a-c846d02ee01d.png)

Wanted behavior:
![Code_-_Insiders_qVCGPpstW2](https://user-images.githubusercontent.com/46263989/179317020-58d8cbcf-63da-4999-a0a3-e4672952a058.png)

**Comment by carsakiller** [comment] 2022-08-06 02:32
Issues with the language server should be reported in its repo. This issue is a duplicate of: https://github.com/sumneko/lua-language-server/issues/599

**Closed** 2022-09-08 13:37 UTC
